# Generated by Django 5.2.5 on 2025-11-23 18:09

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_post_tags"),
    ]

    operations = [
        TrigramExtension(),
    ]
